### ISSUE TITLE
Models and Tables

### ISSUE THREAD

**Issue by alodes999** [alodes999/06-23-project-from-scratch#26]
### games (table name)

<table>
  <tr>
    <th> id </th>
    <th> name </th>
    <th> genre_id </th>
  </tr>
  <tr>
    <th> Primary key (Integer) </th>
    <th> Text </th>
    <th> Foreign key(Integer) </th>
  </tr>
</table>

### genres (table name)

<table>
  <tr>
    <th> id </th>
    <th> name </th>
  </tr>
  <tr>
    <th> Primary key (Integer) </th>
    <th> Text </th>
  </tr>
</table>

### users (table name)

<table>
  <tr>
    <th> id </th>
    <th> name </th>
  </tr>
  <tr>
    <th> Primary key (Integer) </th>
    <th> Text </th>
  </tr>
</table>

### reviews (table name)

<table>
  <tr>
    <th> id </th>
    <th> game_id </th>
    <th> user_id </th>
    <th> review_score </th>
  </tr>
  <tr>
    <th> Primary key (Integer) </th>
    <th> Foreign key (Integer) </th>
    <th> Foreign key (Integer) </th>
    <th> Integer </th>
  </tr>
</table>

**Comment by sumeetjain** [comment]
Some naming convention issues (See https://github.com/omahacodeschool/wiki/blob/master/ruby/naming-things.md)
